/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class ListModeLib */

#ifndef _Included_ListModeLib
#define _Included_ListModeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ListModeLib
 * Method:    runListMode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ListModeLib_runListMode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
